// download AI Analysis as pdf
export const convertToPdf = (latestAnalysis: any, currency_str?: string) => {
  if (!latestAnalysis) {
    alert("No data to export");
    return;
  }

  const win = window.open("", "_blank");

  if (!win) return;

  currency_str = currency_str ?? "₹";

  const formatList = (arr: any[], key: string) => {
    if (!Array.isArray(arr) || arr.length === 0) return "<li>-</li>";

    return arr.map((item) => `<li>${item[key] || "-"}</li>`).join("");
  };

  win.document.write(`
    <html>
      <head>
        <title>MoneyMind Report</title>

        <style>
          body {
            font-family: Arial, sans-serif;
            padding: 40px;
            color: #111827;
            line-height: 1.6;
          }

          h1 {
            margin-bottom: 4px;
          }

          .sub {
            color: #6b7280;
            font-size: 13px;
          }

          .score {
            margin-top: 10px;
            font-size: 18px;
            font-weight: bold;
            color: #2563eb;
          }

          .section {
            margin-top: 24px;
          }

          .section-title {
            font-size: 12px;
            color: #6b7280;
            font-weight: bold;
            margin-bottom: 6px;
            text-transform: uppercase;
          }

          ul {
            padding-left: 18px;
          }

          li {
            margin-bottom: 6px;
          }

          .box {
            background: #f9fafb;
            padding: 12px;
            border-radius: 8px;
          }

          @media print {
            body {
              padding: 20px;
            }
          }
        </style>
      </head>

      <body>

        <h1>💰 MoneyMind Report</h1>
        <div class="sub">AI-powered financial behavior analysis</div>

        <div class="score">
          Score: ${latestAnalysis.score || 0} / 100
        </div>

        <div class="section">
          <div class="section-title">🧠 Personality</div>
          <div class="box">${latestAnalysis.personality || "-"}</div>
        </div>

        <div class="section">
          <div class="section-title">💡 Key Insights</div>
          <ul>
            ${formatList(latestAnalysis.insights, "text")}
          </ul>
        </div>

        <div class="section">
          <div class="section-title">⚡ Action Plan</div>
          <ul>
            ${formatList(latestAnalysis.fixes, "action")}
          </ul>
        </div>

        <div class="section">
          <div class="section-title">📊 Financial Impact</div>
          <div class="box">
            💸 Savings Potential: ${currency_str}${latestAnalysis.impact?.savingsPotential || 0}/month <br/>
            📈 Projected Savings: ${currency_str}${latestAnalysis.impact?.projectedSavings || 0} <br/>
            ⚠️ Risk Level: ${latestAnalysis.impact?.riskLevel || "-"}
          </div>
        </div>

        <div class="section">
          <div class="section-title">📌 Snapshot</div>
          <div class="box">
            Income: ${currency_str}${latestAnalysis.snapshot?.income || 0} <br/>
            Spent: ${currency_str}${latestAnalysis.snapshot?.totalSpent || 0} <br/>
            Savings Rate: ${latestAnalysis.snapshot?.savingsRate || 0}%
          </div>
        </div>

        <div style="margin-top:40px;font-size:11px;color:#9ca3af;">
          Generated by MoneyMind • Behavioral Finance AI
        </div>

        <script>
          window.onload = function() {
            window.print();
            window.onafterprint = () => window.close();
          }
        </script>

      </body>
    </html>
  `);

  win.document.close();
};
